
CREATE DATABASE If NOT EXISTS avail;
use avail;

CREATE TABLE IF NOT EXISTS user (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(30) NOT NULL,
active INT(6) UNSIGNED NOT NULL,
email VARCHAR(50) NOT NULL,
password VARCHAR(32) NOT NULL,
loged_id varchar(40),
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS question (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,

question VARCHAR(150) NOT NULL,
vote INT(6) NOT NULL,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
userid INT(6) UNSIGNED NOT NULL,
FOREIGN KEY(userid) REFERENCES user(id)
);
CREATE TABLE IF NOT EXISTS comment (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
comment VARCHAR(150) NOT NULL,
questionid INT(6) UNSIGNED NOT NULL,
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

userid INT(6) UNSIGNED NOT NULL,

FOREIGN KEY(questionid) REFERENCES question(id)
);
ALTER TABLE comment
ADD FOREIGN KEY (userid) REFERENCES user(id);
insert into user(username,active,email,password,loged_id) values("name",1,"davidaniston0@gmail.com","12345678","4444");